comunity_topics_workflow: add a reminder about milestones
ansible-community/community-topics pull request #125
Opened 2022-08-09 10:22 UTC by Andersson007

Relates to https://github.com/ansible-community/community-topics/issues/122#issuecomment-1197132072

2022-08-09 14:23 UTC, mariolenz approved these changes
LGTM

2022-08-09 15:54 UTC, mariolenz requested changes
Maybe we should clarify the status of the topic when it implies actions related to a future release: When an issue is added to the corresponding milestone, is the topic `implemented` or still `being_implemented` until it's really implemented in the future release?

Personally, I tend to consider it `implemented` in that case. Or, alternatively, have another label to say that this topic is more or less resolved, even if not really implemented yet. Like `scheduled_for_future_release` or similar. And then close it and move it to the `Resolved` column. After all, there's nothing much to do with the _topic_, the doing is tracked in the milestone.

Whether you agree with me or not, I think we should document here what should happen to the topic.

2022-08-15 09:11 UTC, Andersson007 commented
> Maybe we should clarify the status of the topic when it implies actions related to a future release: When an issue is added to the corresponding milestone, is the topic `implemented` or still `being_implemented` until it's really implemented in the future release?
> 
> Personally, I tend to consider it `implemented` in that case. Or, alternatively, have another label to say that this topic is more or less resolved, even if not really implemented yet. Like `scheduled_for_future_release` or similar. And then close it and move it to the `Resolved` column. After all, there's nothing much to do with the _topic_, the doing is tracked in the milestone.
> 
> Whether you agree with me or not, I think we should document here what should happen to the topic.

Good catch! I'm fine with `implemented` + `scheduled_for_future_release`. @felixfontein what do you think? (i don't think we should vote on this or discuss it broadly)

2022-08-15 11:59 UTC, felixfontein commented
Sounds good to me!

2022-08-16 06:54 UTC, Andersson007 commented
@mariolenz @felixfontein added a step about labeling, PTAL

2022-08-16 11:22 UTC, felixfontein commented on community_topics_workflow.md
> +  - [ ] Creates an issue and adds it to the milestone.
```suggestion
  - [ ] Creates an issue in ansible-build-data that references the topic in community-topics, and adds it to the milestone.
```

2022-08-16 12:36 UTC, Andersson007 commented on community_topics_workflow.md
> +  - [ ] Creates an issue and adds it to the milestone.
SGTM, committed, thanks, PTAL

2022-08-16 15:51 UTC, mariolenz approved these changes
LGTM

2022-08-16 19:19 UTC, felixfontein approved these changes

2022-10-03 12:26 UTC, merged

2022-10-03 12:27 UTC, Andersson007 commented
@mariolenz @felixfontein thanks for reviewing!